# Site settings
name: Less Or More
email: 496380369@qq.com
author: yan zi jie
url: https://nishibaiyang.github.io/yanzijie_blog/
resume_site: https://nishibaiyang.github.io/yanzijie_blog/
github: https://github.com/nishibaiyang
baseurl: ""
description: Actually, less is more!
meta_description: 个人博客;知识在于积累
motto: It's our wits that make us men.
banner: 任何带有思考的选择都是对的。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: nishibaiyang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : --
    duoshuo:
        short_name : --
    disqus :
        short_name : --
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light